"""add is_recurring_booking to Booking

Revision ID: bd3e568ffdba
Revises: df64ef784b3c
Create Date: 2026-01-09 00:55:41.701991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3e568ffdba'
down_revision = 'df64ef784b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring_booking', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('is_recurring_booking')

    # ### end Alembic commands ###
