"""Dodanie ID grupy dla zajec cyklicznych

Revision ID: df64ef784b3c
Revises: 34eb71d6d448
Create Date: 2025-11-14 12:37:35.051054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df64ef784b3c'
down_revision = '34eb71d6d448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_group_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_training_session_recurrence_group_id'), ['recurrence_group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_session_recurrence_group_id'))
        batch_op.drop_column('recurrence_group_id')

    # ### end Alembic commands ###
